apiVersion: v1
kind: Service
metadata:
  name: movi-svc
spec:
  selector:
    app: mymovips-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer